### ISSUE TITLE
Returning the fetched object

### ISSUE THREAD

**Issue by Calvin087** [fitnessforlife/mfp#41]
Apologies to start as I can't find another way to ask questions about this project.

```js
mfp.fetchDateRange('username', '2014-09-15', '2014-09-18', 'all', function(data){
  console.log(data); // why can I log the data
});

mfp.fetchDateRange('username', '2014-09-15', '2014-09-18', 'all', function(data){
  return data // but I can't return this object and use it elsewhere?
});
```

How does someone actually return this object when called from another function / file.
Many thanks.

**Comment by andrewzey** [comment]
@Calvin087 This is an inherent part of how callbacks work in Javascript. I highly recommend mastering this chapter: https://eloquentjavascript.net/11_async.html and then reading https://medium.com/@mandeepkaur1/the-ultimate-guide-to-javascript-promises-ee4f1274e5c6

Once you've mastered that material, it will become clear how to "wrap" callback based functions with promises which also will enable you to use async / await syntax.

Hope that helps!

**Comment by Calvin087** [comment]
@andrewzey , thank you. Really appreciate the help. Will dig into those links immediately and thanks for making this package.

**Comment by andrewzey** [comment]
@Calvin087 My pleasure!
